version: '3.3'

services:
    mysql: 
      image: mysql:latest
      environment:
        MYSQL_USER: devbook
        MYSQL_PASSWORD: localhost123
        MYSQL_ROOT_PASSWORD: root123
      ports:
        - "3306:3306"
      networks:
        - mysql-connect

networks:
  mysql-connect:
    driver: bridge